[package]
name = "aad"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
ordered_hash_map = "0.4.0"
uuid = { version = "1.17.0", features = ["v4"] }
global_counter = "0.2.2"
sorted-vec = "0.8.6"
